import { useNavigate } from 'react-router-dom'
import { ChevronLeft, Clock, Zap, BookOpen, AlertTriangle } from 'lucide-react'
import { useAuth } from '../contexts/AuthContext'
import BottomNav from '../components/BottomNav'
import GreenHero from '../components/GreenHero'

const PLAN_TYPES = [
  { label: 'Complete Class 9',  duration: '30–90 days', desc: 'All subjects, all chapters, balanced daily schedule', icon: '📚', available: false },
  { label: 'Single Subject',    duration: '7–30 days',  desc: 'One subject — focused deep study',                  icon: '🎯', available: false },
  { label: 'MDCAT 60-Day',      duration: '60 days',    desc: 'Complete PMC syllabus with daily targets',           icon: '🩺', available: false },
  { label: 'Exam Emergency',    duration: '7 days',     desc: 'Most important topics only — pre-exam crash course', icon: '⚡', available: false },
]

export default function StudyPlanScreen() {
  const navigate = useNavigate()
  const { profile } = useAuth()

  return (
    <div className="flex flex-col h-screen bg-gray-50 dark:bg-slate-950">
      <GreenHero>
        <button onClick={() => navigate(-1)} className="text-brand-200 mb-2 flex items-center gap-1 text-xs">
          <ChevronLeft size={14} /> Back
        </button>
        <div className="flex items-center gap-3 mb-3">
          <span className="text-3xl">📅</span>
          <div>
            <h1 className="text-xl font-black">Study Plan</h1>
            <p className="text-brand-100 text-xs">AI-Generated · Personalised for your exam</p>
          </div>
        </div>
        <div className="flex gap-2">
          {[
            { val: profile?.class_level ?? 'Class 9', label: 'Your Class' },
            { val: 'Coming Soon', label: 'Status' },
          ].map(({ val, label }) => (
            <div key={label} className="bg-white/20 rounded-xl px-3 py-2 text-center">
              <div className="text-sm font-black">{val}</div>
              <div className="text-[10px] text-brand-100">{label}</div>
            </div>
          ))}
        </div>
      </GreenHero>

      <div className="flex-1 overflow-y-auto px-4 py-4 flex flex-col gap-4">

        {/* Honest coming-soon state */}
        <div className="bg-slate-900 rounded-2xl p-5 flex flex-col items-center text-center gap-3">
          <div className="text-4xl">🤖</div>
          <div className="text-sm font-black text-brand-400">AI Study Plan — Coming Soon</div>
          <p className="text-xs text-slate-300 leading-relaxed">
            Your personalised study plan will be generated by AI based on your weak chapters,
            available time before your exam, and your daily quiz performance.
            This feature launches once your subject content is fully live.
          </p>
          <div className="w-full bg-white/10 rounded-xl p-3 flex items-start gap-2 text-left">
            <AlertTriangle size={14} className="text-amber-400 flex-shrink-0 mt-0.5" />
            <span className="text-[11px] text-slate-300 leading-relaxed">
              In the meantime — the best study plan is simple: open a chapter, read the notes,
              do the MCQs, check your weak areas in Progress, repeat.
            </span>
          </div>
        </div>

        {/* Quick actions they can do right now */}
        <div>
          <div className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-2 dark:text-slate-500">Study Right Now</div>
          <div className="grid grid-cols-2 gap-3">
            {[
              { label: 'Browse Subjects', icon: BookOpen, color: 'from-brand-100 to-brand-50 text-brand-700 dark:text-brand-400', path: '/subjects' },
              { label: 'Quick Quiz',      icon: Zap,      color: 'from-blue-100 to-blue-50 text-blue-700 dark:from-blue-950/50 dark:to-blue-900/30 dark:text-blue-400', path: '/quiz' },
              { label: 'Past Papers',     icon: Clock,    color: 'from-violet-100 to-violet-50 text-violet-700 dark:from-violet-950/50 dark:to-violet-900/30 dark:text-violet-400', path: '/past-papers' },
              { label: 'My Progress',     icon: AlertTriangle, color: 'from-amber-100 to-amber-50 text-amber-700 dark:from-amber-950/50 dark:to-amber-900/30 dark:text-amber-400', path: '/progress' },
            ].map(({ label, icon: Icon, color, path }) => (
              <button
                key={label}
                onClick={() => navigate(path)}
                className={`bg-gradient-to-br ${color} rounded-2xl p-4 text-center active:scale-95 transition-all`}
              >
                <Icon size={20} className="mx-auto mb-1.5" />
                <div className="text-xs font-bold">{label}</div>
              </button>
            ))}
          </div>
        </div>

        {/* Plan types — shown as a preview of what's coming */}
        <div>
          <div className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-3 dark:text-slate-500">Plan Types — Preview</div>
          <div className="flex flex-col gap-2">
            {PLAN_TYPES.map(({ label, duration, desc, icon }) => (
              <div key={label} className="bg-white rounded-2xl shadow-sm p-3 flex items-center gap-3 opacity-60 dark:bg-slate-800">
                <div className="w-10 h-10 bg-brand-50 rounded-xl flex items-center justify-center flex-shrink-0 text-xl dark:bg-brand-950/40">
                  {icon}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-xs font-bold text-slate-900 dark:text-slate-100">{label}</div>
                  <div className="text-[10px] text-gray-400 mt-0.5 dark:text-slate-500">{desc}</div>
                </div>
                <span className="text-[9px] bg-gray-100 text-gray-400 font-bold px-2 py-1 rounded-full flex-shrink-0 dark:bg-slate-700 dark:text-slate-500">Soon</span>
              </div>
            ))}
          </div>
        </div>

      </div>

      <BottomNav />
    </div>
  )
}